#!/usr/bin/env php
<?php
namespace think;

// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

// 应用初始化
//(new App())->console->run(); //旧的框架类
(new \extend\think\App())->console->run();//继承旧的 修改后的框架类